### ISSUE TITLE
Missing des_teff_g.fits file

### ISSUE THREAD

**Issue by JosephKarpinski** [noaodatalab/aas237-splinter-session#2]
Hi,

Where can one download the "des_teff_g.fits" file used in 
'https://github.com/astro-datalab/aas237-splinter-session/blob/main/ExploringDES_DGs.ipynb'

# Load teff map created by Knut earlier, and use as weight map
teff = hp.read_map('des_teff_g.fits',nest=True)

Thanks!

**Comment by rnikutta** [comment]
Pinging @knutago Knut do you still have the fits file somewhere?

**Comment by knutago** [comment]
The file is larger (~800 MB) than GitHub allows, so I've posted to a publicly viewable Google Drive folder here: https://drive.google.com/file/d/1PnaDGcmvY3_ondCmq-r-TnDSvBoD9jOF/view?usp=sharing

**Comment by JosephKarpinski** [comment]
Thank you!
